'use strict';
let mount = require('./mount');

module.exports = function() {
  return {
    apps: [],
    // A koaApp is generated by calling koa() which creates a Koa server app instance
    init: function(koaApp) {
      this.koaApp = koaApp;
      this.routes = routes.init(koaApp);
      this.mount = mounter(this);
      return this;
    },
    start: function(koaApp) {
      if (koaApp) this.init(koaApp);
      this.koaApp.start();
    }
  };
}
