'use strict';
let routes = require('./routes');

module.exports = function() {
  return {
    apps: [],
    // A koaApp is generated by calling koa() which creates a Koa server app instance
    init: function(koaApp) {
      this.koaApp = koaApp;
      this.routes = routes.init(koaApp);
      return this;
    },
    // config: Object
    // state: Object, findTemplate: function
    mount: function(name, config) {
      // add app to registry
      // mount route using config
      this.apps.push(name);
      this.routes.add(name, config);
    },
    mountApps: function(apps) {
      for (let app of apps) {
        this.mount(app.name, app.config);
      }
    },
    start: function(koaApp) {
      if (koaApp) this.init(koaApp);
      this.koaApp.start();
    };    
  }
}
