'use strict';
let mounter = require('./mounter');
let routes = require('./routes');
let koa = require('koa');

module.exports = function() {
  return {
    apps: [],
    // A koaApp is generated by calling koa() which creates a Koa server app instance
    init: function(koaApp) {
      this.koaApp = koaApp;
      this.routes = routes.init(this.koaApp);
      this.mount = mounter(this);
      return this;
    },
    start: function(koaApp) {
      if (koaApp) this.init(koaApp);
      this.koaApp.koaServer.start();
    }
  };
}
